# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-04"

[[extensions]]
type = "ui_extension"
name = "pos-ui-x-ezzat"

handle = "pos-ui-x-ezzat"
description = "A typescript-react POS UI extension"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Tile.tsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.tsx"
target = "pos.home.modal.render"

[[extensions.targeting]]
module = "./src/CustomerBlock.tsx"
target = "pos.customer-details.block.render"

[[extensions.targeting]]
module = "./src/CustomerTile.tsx"
target = "pos.customer-details.action.menu-item.render"

[[extensions.targeting]]
module = "./src/CustomerTileDetails.tsx"
target = "pos.customer-details.action.render"
